{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{% trans 'SMS Gateway' %}{% endblock %}

{% set active_menu = 'smsgateway' %}

{% block content %}

<div class="widget">
    <div class="head">
        <h5>{% trans 'SMS Gateway' %}</h5>
    </div>

    {% if plugins %}
    <div class="help">
        <h3>{% trans 'Installed Plugins' %}</h3>
    </div>
    <div class="body">
				<table class="tableStatic wide">
					<tbody>
						{% for code, plugin_title in admin.smsgateway_plugin_get_pairs %}
						<tr {% if loop.first %}class="noborder"{% endif %}>
							<td>{{ plugin_title }}</td>
							<td class="actions" style="width:13%">
							<a class="bb-button btn14" href="{{ 'smsgateway/plugin'|alink }}/{{ code }}"><img src="images/icons/dark/pencil.png" alt=""></a>
							<!-- a class="bb-button btn14" href="{{ 'smsgateway/plugin'|alink }}"><img src="images/icons/dark/pencil.png" alt=""></a-->
							</td>
            </tr>
						{% else %}
            <tr>
							<td colspan="2">{% trans 'The list is empty' %}</td>
						</tr>
						{% endfor %}						
						</tbody>
					</table>					
    </div>
    {% endif %}		
		
		


</div>

<div class="widget">
    <div class="head">
        <h5>{% trans 'README' %}</h5>
    </div>
    
    <div class="body list arrowBlue">
        {{ guest.smsgateway_readme|markdown }}
    </div>
</div>

{% endblock %}