{% set params = admin.smsgateway_config_get({"code": code }) %}

<form method="post" action="{{ 'api/admin/smsgateway/config_save'|link }}" class="mainForm api-form" data-api-msg="{% trans 'Configuration updated' %}">
    <div class="help">
        <h3>{% trans 'Boxis SMS Gateway configuration' %}</h3>
        <p>{% trans 'Configure this for Boxis SMS Gateway' %}</p>
    </div>
    
    <fieldset>
        <div class="rowElem noborder">
            <label>{% trans 'API Key:' %}</label>
            <div class="formRight">
                <input type="text" name="api_key" value="{{params.api_key}}" placeholder="{% trans 'Example custom value' %}"/>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem noborder">
            <label>{% trans 'E-mail:' %}</label>
            <div class="formRight">
                <input type="text" name="username" value="{{params.username}}" placeholder="{% trans 'Example custom value' %}"/>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem noborder">
            <label>{% trans 'Sender name:' %}</label>
            <div class="formRight">
                <input type="text" name="sender_name" value="{{params.sender_name}}" placeholder="{% trans 'Example custom value' %}"/>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem noborder">
            <label>{% trans 'Highest priority:' %}</label>
            <div class="formRight">
                <input type="checkbox" name="high_priority" class="smc" value="{{ params.high_priority }}">
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem noborder">
            <label>{% trans 'Client field:' %}</label>
            <div class="formRight">
                <input type="text" name="client_field" value="{{params.client_field}}" placeholder="{% trans 'Example custom value' %}"/>
            </div>
            <div class="fix"></div>
        </div>

        <input type="submit" value="{% trans 'Update' %}" class="greyishBtn submitForm" />
        <input type="hidden" name="ext" value="mod_smsgateway" />
				<input type="hidden" name="plugin_code" value="boxis" />
    </fieldset>
</form>		
